name: Deploy to Production

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: arsalanses/docker-backup-mysql
  APP_PATH: docker-backup-mysql

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      packages: write
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        file: ./dockerfiles/Dockerfile.mysql9
        cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE_NAME }}:latest
        cache-to: type=inline
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:${{ github.run_id }}
          ghcr.io/${{ env.IMAGE_NAME }}:latest

  trivy:
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 5
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.29.0
      with:
        image-ref: 'ghcr.io/${{ env.IMAGE_NAME }}:${{ github.run_id }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'
        scanners: 'vuln'
      env:
        TRIVY_DISABLE_VEX_NOTICE: true
